### ISSUE TITLE
Changed backend CSS- and JS-files aren't loaded after a CONTENIDO update

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#100]
When we change backend CSS- and JS-files in CONTENIDO and deliver them with a new CONTENIDO version, the changed files won't be loaded by the browser, when the user logs in in backend after a CONTENIDO update.

Browsers cache files, and they won't load them. Some user have reported issues, e. g. JavaScript errors, in the backend and the reason was the browser cache.

We need a way to force the browser to reload changed files, and the easiest way is to add a parameter to the file url:
```
<script type="text/javascript" src="scripts/contenido.js?v=filehash"></script>
<script type="text/javascript" src="scripts/general.js?v=filehash"></script>

```
The value `filehash` could be a md5 of the CONTENIDO version.

Some backend JavaScript files are configured in `data/config/{environment}/config.misc.php` and rendered in `contenido/includes/chains/include.chain.template.parsetemplate.php`. But we have also other places (templates, includes) where link- and script-tags are rendered in order to load CSS- and JS-files.

Tags:
backend, ui

**Comment by tone2tone** [comment]
It could be that our problem here goes deeper if the whole login page in total is cached. For whatever reason, AFTER login, meta tags are set to:
```
    <meta http-equiv="expires" content="0">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="pragma" content="no-cache">
```
The login page though doesn't show those entries. It might help to avoid problems if we add this to login page. 
I can add it to main.loginform.html if you wish.

**Comment by muratpurc** [comment]
We need a way to force the loading of changed ressource files, and meta tags won't be sufficient. The ressource files should have a parameter which forces the browser to load the new files instead to load them from the chache.

Each time, when I change a ressource file, I update the version parameter of the url references to the file, see:
https://github.com/CONTENIDO/CONTENIDO/blob/develop/contenido/templates/standard/header.html

The following line containg the md5 hash of the modified date:
`<script type="text/javascript" src="scripts/rowMark.js?v=4ff97ee40f1ac052f634e7e8c2f3e37e"></script>`
 
This is not a perfect solution but it works well.  The problem is, that we can't solve this on the server side with PHP, since some ressources are loaded via JavaScript.

**Comment by tone2tone** [comment]
@purcaholic Okay then, question is: does this really have to apply for ALL calls of backend js/css files? There are LOTS... Or would it suffice for the time being to at least do it for files called in config.misc.php? 
Shall we come up with a global variable or constant that can be added bit by bit, and if so, which way would you prefer (variable or constant)?

**Comment by muratpurc** [comment]
@tone2tone We should aim for a solution, that is usable for the backend and also for the frontend.
Both areas have the same issue, when it comes to load new versions of changed js-/css-files.

Using a variable or a constant would fix the issue in the backend, but not in the frontend.

While we can use one value for all resource files being loaded in the backend, access to the backend is limited to few people, the frontend should handle each resource file separately, otherwise a change in one file would affect the loading of all frontend files (css & js).

Implementing two different solutions (frontend & backend) makes the CONTENIDO code difficult to maintain.

**Comment by tone2tone** [comment]
@purcaholic When you talk about "frontend": are you talking about js/css files that are included in a webfront layout? If so, I do not see comparable issues. Contenido ( = the backend ) might be updated, yet the source code of the frontend page ( the real website ) mostly has no changed css or js files, unless it implements updates js/css routines from contenido (which in most cases I do not have, apart from contenido_backend.css, but this one I update myself from time to time and I know I have to bruteforce a page refresh now and then to make my backend editing view correct).
Or are you talking about something else?
Plus: what way of solving this problem DO you have in mind if variable or constant are no solution?

**Comment by muratpurc** [comment]
@tone2tone 

> ...are you talking about js/css files that are included in a webfront layout?...

Yes, I mean the frontend resource files (js, css) used to render the page for clients.


We should aim for a solution, that is usable for both backend (CONTENIDO backend) and frontend (client pages). 

A variable or a constant would not work for both. We should implement a functionality for auto-versioning JS- and CSS-files, like described in the link below:
https://stackoverflow.com/questions/118884/how-to-force-the-browser-to-reload-cached-css-and-javascript-files/118886#118886

Instead of creating file names like `base.1234567890.css` and to rewrite them in the .htaccess, it would be enough to add a version parameter like `base.css?v=1234567890`.

This approach can be used in the backend and in the frontend, and it works for each single asset file.

**Comment by gonatan** [comment]
What about a totally different approach?

It's not CONTENIDOs responsibility to assertain that the client
receives the newest version of a (HTTP) ressource ...  it's the webservers!

If we just amend the proposed .htaccess in AMR we could say that
JS & CSS ressources are valid no more than a reasonable amount of time.

I found these two alternatives:

    <IfModule mod_expires.c>
        ExpiresActive On
        ExpiresByType text/css "access plus 1 week"
        ExpiresByType text/javascript "access plus 1 month"
        ExpiresByType application/javascript "access plus 1 month"
    </IfModule>

    <ifModule mod_headers.c>
        <filesMatch ".(js)$">
            Header set Cache-Control "max-age=2592000, public"
        </filesMatch>
        <filesMatch ".(css)$">
            Header set Cache-Control "max-age=604800, public"
        </filesMatch>
    </ifModule>

This would
- be feasible for backend and frontend ressources alike
- would not be difficult to maintain as CONTENIDO itself is not modified

Any thoughts about this?

**Comment by muratpurc** [comment]
Hi @gonatan we need a way to serve changed asset files immediately, your proposal would serve the files with the cache flag. A changed asset file would be requested by the client after the defined cache lifetime, not after the file has been changed.

**Comment by gonatan** [comment]
@purcaholic Thats right! Will it be possible to add rewrite rules instead that just append the v-Query as you proposed then? I'm just looking for a solution that helps us to minimize the effort to achieve the goal we already agreed on.

**Comment by dceonline** [comment]
Maybe it' s possible to set a flag, if files were changed in backend. Using this flag one may generate a kind of timestamp or hash and ad it as parameter to all css and js files while generating frontendview.

**Comment by muratpurc** [comment]
We should also take into consideration that files could not only be changed via the backend, when editing them, but also by an update, e.g., when a dev uploads files via (S)FTP.

My proposal would be an asset helper which checks the timestamp (aka `filetime`) of the asset file and generates a unique id for it. This could be done once for each used asset file within a page request lifecycle.

**Comment by muratpurc** [comment]
Hi everyone,

a new asset helper (`cAsset`) feature has been implemented, it’s purpose is to add a version parameter to served asset files (js & css). The current implementation adds the file modification time to the asset file URL as a query parameter, which forces any modified asset files being requested again, at least in most cases (some proxies may still cache GET requests with different query parameter).

**Example:**

````
scripts/contenido.js -> scripts/contenido.js?v=123456789
````

The CONTENIDO sources now use the asset helper to reference JS- or CSS-files, it is integrated in following areas:
-	Backend templates (old style and Smarty)
-	Backend PHP code
-	Frontend code generation (for collected page JS-/CSS-files)
-	Optional, in frontend layouts
-	Optional, in frontend templates (smarty)
-	Optional, in frontend PHP code


**Usage in old backend templates:**

Syntax is `{_ASSET(path/to/file.ext)_}`, e.g.

```
<link rel="stylesheet" type="text/css" href="{_ASSET(styles/contenido.css)_}">
<script type="text/javascript" src="{_ASSET(scripts/contenido.js)_}"></script>
```

**Usage in new backend templates (Smarty):**

There is a new Smarty modifier plugin function `con_asset_backend`, which can be used in smarty template files, e.g.:

```
<link rel="stylesheet" type="text/css" href="{'styles/contenido.css'|con_asset_backend}">
<script type="text/javascript" src="{'scripts/contenido.js'|con_asset_backend}"></script>
```

**Usage in backend code (PHP scripts) directly:**

```
echo '<link rel="stylesheet" type="text/css" href="' . cAsset::backend('styles/contenido.css') . '">';
echo '<script type="text/javascript" src="' . cAsset::backend('scripts/contenido.js') . '"></script>';
```

**Optional usage in frontend templates (Smarty):**

There is a new Smarty modifier plugin function `con_asset_frontend`, which can be used in frontend smarty template files, e.g.:

```
<link rel="stylesheet" type="text/css" href="{'css/main.css'|con_asset_frontend}">
<script type="text/javascript" src="{'js/main.js'|con_asset_frontend}"></script>
```

The asset helper uses the current client by default, but you can also pass the client parameter to the modifier function, e.g.
```
{* Use the client id 2 *}
{'js/main.js'|con_asset_frontend:2}
```

**Optional usage in frontend layouts directly:**

```
<link rel="stylesheet" type="text/css" href="<?php echo cAsset::frontend('css/main.css'); ?>" />
<script type="text/javascript" src="<?php echo cAsset::frontend('js/main.js'); ?>"></script>
```

Here, too, you can pass the id of the client as the second parameter, e.g.

```
<?php echo cAsset::frontend('js/main.js', 2); ?>
```

The usage of `cAsset::frontend()` is possible, but I recommend a more performant solution for the frontend layout, e.g. a custom container, where we can set the asset version query parameter during the code generation.

**Optional usage in frontend code (PHP scripts, e.g. in modules, plugins, etc.) directly:**

```
echo '<link rel="stylesheet" type="text/css" href="' . cAsset::frontend('css/main.css') . '">';
echo '<script type="text/javascript" src="' . cAsset::frontend('js/main.js') . '"></script>';
```

**Some final notes:**

-	URLs to asset files must be relative from the backend path or clients’ frontend path, fully qualified or schemeless URLs are not accepted.
-	The file modification time will be retrieved only once per file for each request lifecycle.
-	Asset files being loaded by the backend UI (`Con.Loader.get()`) are excluded from this cache prevention strategy, but they use their own, they just add current date (YYYMMDD) to the requested asset files, which forces them being re-requested from the server daily.
-	You can implement your own logic to generate an custom asset file path with the version hash by using the provided CEC hooks. CEC hook `Contenido.Backend.Asset` is for the backend assets, and CEC hook `Contenido.Frontend.Asset` for the frontend assets. Registered hook functions get the asset file URL, can do their custom modification, e.g. (change `scripts/contenido.js`  to `scripts/contenido.123456789.js`) and should return the modified asset file URL. The hook function for the frontend assets gets additionally the id of the client as the second parameter, in case someone needs this.
-	We have two new small features as a goodie, the `cHTMLLinkTag::stylesheet()` to generate a link tag for referencing external styles and `cHTMLScript::external()` to generate a script tag for referencing external JavaScript.

**Comment by gonatan** [comment]
GREAT!!!
