### ISSUE TITLE
Form Assistant Plugin - Add "Reply-To" option to system mail setting

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#130]
The form setting should provide the option to use the email address, filled-in in the form, as a reply-to address for the system email.

See topic in forum:
https://forum.contenido.org/viewtopic.php?f=116&t=43927

**Comment by ChristianJohn-Softwareentwicklung** [comment]
If no reply_to_email is set, swift-mailer generates an error: "Address in mailbox given [] does not comply with RFC 2822, 3.6.2." because replyTo var in class.pifa,mailed_form_processor.php is empty. 
In class.pifa.form.php line 610 only checks if var exists, not if it is empty
>             if (array_key_exists('replyTo', $opt)) {
Need change to 
>            if (array_key_exists('replyTo', $opt) && !empty($opt['replyTo'])) {
