### ISSUE TITLE
Remove PHP 5.4 support

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#137]
File functions.php54.php is used to fix encoding related functions for PHP 5.4.

CONTENIDO 4.10 requires at least PHP 7, file functions.php54.php and the usage of the functions in the file can be removed.

**Comment by tone2tone** [comment]
Okay, what's the exact plan here? Other than the filename suggests, functions.php54.php holds some encoding/decoding function that are used a LOT throughout contenido, not only when 5.4 is running (example code see below). 
Questions:
- Shall the functions in this file just be stripped of its 5.4 related things, the rest remains untouched, even the file name?
- Or shall we strip as above, but rename the file and adapt filename includes accordingly?
- Or shall we strip the functions and incorporate them into functions.encoding.php, which I think would require to include functions.encoding.php where (as at the moment) functions.php54.php is included (startup process, setup process and such)?
- Or shall functions.php54.php deleted alltogether and ALL function calls through all files shall be deleted too? Affected functions are: conHtmlSpecialChars, conHtmlEntityDecode, conHtmlentities, conGetHtmlTranslationTable

Example function:
```
if (function_exists('conHtmlSpecialChars') == false) {

    /**
     *
     * @param string $value
     * @param int|string $flags
     * @param string $encoding
     * @return string
     */
    function conHtmlSpecialChars($value, $flags = '', $encoding = '') {
        $isPhp54 = conPhp54Check();

        if ($encoding == '') {
            $encoding = cRegistry::getEncoding();
        }

        // consider case that encoding could not be determined
        if (empty($encoding)) {
            $encoding = null;
        }

        if ($isPhp54 == 1) {
            $flags = ($flags == '') ? ENT_COMPAT | ENT_HTML401 : $flags;
            $encoding = ($encoding == '') ? 'UTF-8' : $encoding;
        } else {
            $flags = ($flags == '') ? ENT_COMPAT : $flags;
        }

        return htmlspecialchars($value, $flags, $encoding);
    }

}
```

**Comment by muratpurc** [comment]
@tone2tone  My advice would be simple and pragmatic. It is sufficient when we strip all PHP5 related logic from functions.php54.php and keep the file. Everything else would lead to more changes, which means a higher risk to break something else or break the CONTENIDO installation of users out there.
