### ISSUE TITLE
Add Support for SVG and WEBP

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#153]
Add support for processing images of type SVG and WEBP in functions.api.images.php.

NOTE:
SVG needs no processing, but it should be returned as it is.

**Comment by tone2tone** [comment]
SVG support basically seems to work, as long as htaccess is allowing it. Contenido's own teaser module relies on its own image editor to produce cached versions through cApiImg-functions. While it reworks jpg files, it leaves svg files as is and uses its original upload path. 
Any need for further amendments here?
I have no experience wit webp files so far. Will do some testing with those at a later stage.

**Comment by tone2tone** [comment]
I can get both to work generally, SVG not a problem. Webp though has issues. With a detected gd2 routine present, I get a cached result when cApiImgScale processes it through its cApiImgScaleHQ function, BUT even though I tell the function to keep the fileType, it won't, and the result looks like a rough lego version of the original. 
Any one with better experience in linking GD2 with webp? If there are problems with GD2 support of this file type right now, we could also route webp through as we do with svg to start with, which enables at least the usage of such files in general.
