### ISSUE TITLE
Replace usage of strtolower and strtoupper against proper mbstring functions

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#158]
Replace usage of strtolower und strtoupper against usage of proper mbstring functions in class cStringMultiByteWrapper.

See also related topic in forum:
https://forum.contenido.org/viewtopic.php?t=44149

**Comment by tone2tone** [comment]
I am sorry to say there are lots of files with strtolower and strtoupper references where no changes have been made. I think they should all be replaced with cString::toLowerCase and cString::toUpperCase. If so, I'd take on the task.

**Comment by muratpurc** [comment]
@tone2tone all occurrences of  strtolower or strtoupper in CONTENIDO core where changed against the proper cString* functions.

Remaining strtolower or strtoupper functions are not part of CONTENIDO core, they belong to third party libraries like Smarty or SwiftMailer.

It is not a good idea to change used third party libraries. If nessessary,  a update of used third party libraries should be the first option.

Almost all strtolower or strtoupper in Smarty and SwiftMailer are used in variables having technical names or ascii values, there is no need to use multibyte safe string functions..

**Comment by tone2tone** [comment]
@purcaholic I see. In the patched version I put online as a quick&dirty 7.4-version, I patched ALL occurences (but not with cString, just with its original php equivalent) as this was easier to auto-replace. But I see your point that there is no need with third-party-tools and technical names. Will keep it in mind though as I have installations where we can validate if everything goes right or wrong. :-)
