### ISSUE TITLE
Plugin Newsletter: PHP warnings count()

### ISSUE THREAD

**Issue by dceonline** [CONTENIDO/CONTENIDO#177]
See forum -> https://forum.contenido.org/viewtopic.php?p=181711#p181711

**Comment by tone2tone** [comment]
The line numbers for the specified error log messages do not longer fit for 4.10.1
The "count" error occurs in line 138 in include.recipients_edit.php.
`if (count($aMessages) > 0) {`
Going backwards through source code, it seems $aMessages is always filled in array-style, and this is why the error message seems odd that this is not a countable item. I suspect the array isn't properly instantiated in line 64:
`$aMessages = [];`
Might be better to go along with
`$aMessages = array();`
Update: I checked with 4.10.0 versions, and for some reasons the instantiation there was aray() while in 4.10.1 it has been changed to [] which is rather "cold filling" a non-existent array at the time.
Thoughts?

**Comment by tone2tone** [comment]
Okay... re include.recipients_edit.php I don't think there can be any problem with the source code in develop-branch. Starting with line 64, $aMessages is properly initiated, the following if-section can be ignored and then we have if count(). Same goes for include.recipients.group_edit.php, starting from line 66. 
I don't know what the user who reported the problem did to produce these error messages, but they CAN'T be....
I also created new recipient groups and defined them as test mail standard. All settings were properly saved, all time, and still there when I got back to those sections of the newsletter configuration.

**Comment by muratpurc** [comment]
@tone2tone those `coun()` warnings are not valid anymore. Both files (`include.recipients_edit.php` and `include.recipients.group_edit.php`) where changed meanwhile and the warnings can't happen.

I suspect that the reporter references the CONTENIDO release 4.10.1 and not the current development branch.

**Comment by tone2tone** [comment]
@purcaholic Can this topic be closed then? Plz do so if possible.

**Comment by muratpurc** [comment]
@dceonline can we close the ticket or is this bug still valid?

**Comment by dceonline** [comment]
I will test it today.

**Comment by gonatan** [comment]
The afore linked forum post explicitly states that the error occured w/ CONTENIDO 4.10.0:
> Habe es gerade noch an einer 4.10.0 gestestet.

**Comment by muratpurc** [comment]
This issue doesn't exists anymore in current development branch, therefore I'm closing this ticket.
