### ISSUE TITLE
Activated plugin which is missing in file system leads to subsequent errors

### ISSUE THREAD

**Issue by tone2tone** [CONTENIDO/CONTENIDO#208]
After merging the last pull requests, somewhen around 2021-08-24 the menus
- administration / user / areas and
- administration / groups / areas
are not accessible anymore. I get a 500 error code when clicking those submenus and have no idea, where the general error might be. It worked (even though in a partially broken manner) with the develop branch before my first pull requests were merged.

Edit: Kind of false alert. For testing purposes, I only switched /contenido folders, BUT the original one had one of my own plugins, whilst the second one didn't have it on file. Therefor, the above mentioned pages crashed with plugin missing. Nevertheless, it's a bit of a bugger that momentarily this error is not caught.

**Comment by muratpurc** [comment]
@tone2tone plugins will be loaded after successfull existence check of the plugin configuration file `config.plugin.php`. CONTENIDO won't load an installed and active plugin, unless the plugin configuration file couldn't be found.

**Comment by tone2tone** [comment]
@purcaholic Sure. Thing is: if it can't be found, it would be better to get some information, either in errorlog or whereever. To me, this is a usecase that's often happening, and I keep forgetting that a missing plugin is the source of evil now and then...
My usecase is: I have an installation with my own plugins. I want to update the system, copy over the new contenido folder and forget to incorporate my own plugin folders. I do the update (not a problem), log in (mostly not a problem), navigate through the system (mostly no problem too), but then somewhen an error occurs (like the one where "all of a sudden" an area like group rights / area is not showing). 
At some stage, the system tries to load all plugins according to the database, and there MUST be a way to then determine that config.plugin.php is not there and at least throw an error on it. 
What do you think and can you direct me to the file where this is done?

**Comment by tone2tone** [comment]
To me it would be helpful if in functions.includePluginConf.php, the if-clause starting ag line 34 would come with an else condition, BUT I tried to log an error with `throw new cException('blabla')` which caused the function file to crash, no idea why.
What else could we do with the else condition here?

```
        if (is_dir($pluginFolder . $pluginName . '/')) {
            $plugins[] = $pluginName;
			} else {
           // log or something
	}
```

**Comment by muratpurc** [comment]
@tone2tone Use `cWarning()` instead throwing an Exeption. 

```
// For missing plugin folder
cWarning(__FILE__, __LINE__, 'Plugin blabla folder does not exist.');

// For missing plugin configuration file
cWarning(__FILE__, __LINE__, 'Plugin blabla configuration file is missing.');
```

**Comment by tone2tone** [comment]
@purcaholic Thanks, cWarning is perfect. I will create a pull request and rename this topic accordingly as its focus shifted over time.
