### ISSUE TITLE
Pifa Tables in Database still using MyIsam Engine

### ISSUE THREAD

**Issue by Faar400** [CONTENIDO/CONTENIDO#225]
In general all Database engines already signed as InnoDB, but some plugins don't.
In example con_pifa tables.
If it is not necessary to have MyIsam here, it should be changed to innoDB perhaps.
The "messages"-Plugin is using MyIsam too, and perhaps some plugins more.
source:
https://github.com/CONTENIDO/CONTENIDO/blob/develop/contenido/plugins/form_assistant/plugin_install.sql

**Comment by tone2tone** [comment]
Do I stand correct that the entry "Engine=blabla" can be deleted (instead of changed to something "correct") when installing a plugin? IMHO it is unnecessary.

**Comment by Faar400** [comment]
If there is no explizit need for "Volltextsuche", then it should be possible to delete this entry.
Here some more info: https://spacehost.de/innodb-oder-myisam/

**Comment by muratpurc** [comment]
This issue can be closed, all tables will have InnoDB by default on a new CONTENIDO installation, see Ticket #410
