### ISSUE TITLE
Example data is broken

### ISSUE THREAD

**Issue by kw-pr** [CONTENIDO/CONTENIDO#226]
If I install using the example data it fails with:

```
[2021-09-20 13:05:20] Warning: "Database failure: 1103 (Incorrect table name '!
PREFIX!_content
') - /setup/index.php?c=db&step=29 INSERT INTO `!
PREFIX!_content
`
(`idcontent`, `idartlang`, `idtype`, `typeid`, `value`, `version`, `author`, `created`, `lastmodified`) VALUES
(3, 3, 20, 5, '<?xml version="1.0" encoding="utf-8"?>\n<teaser><title>Teaser</title><category>1</category><count>6</count><style>cms_teaser_style_blog.html</style><manual>false</manual><start>true</start><source_head>CMS_HTMLHEAD</source_head><source_head_count>1</source_head_count><source_text>CMS_HTML</source_text><source_text_count>1</source_text_count><source_image>CMS_IMG</source_image><source_image_count>1</source_image_count><filter></filter><sort>creationdate</sort><sort_order>asc</sort_order><character_limit>400</character_limit><image_width>100</image_width><image_height>75</image_height><manual_art></manual_art><image_crop>false</image_crop><source_date>CMS_DATE</source_date><source_date_count>1</source_date_count></teaser>\n', '', 'sysadmin', NOW
(), NOW
())
" at reportHalt() [class.db.driver.handler.php(1009)]
	reportHalt() called in file class.db.driver.handler.php(981)
	halt() called in file class.db.driver.handler.php(702)
	query() called in file functions.sql.php(48)
	injectSQL() called in file include.db.controller.php(99)
	include() called in file index.php(43)
```

This is because in `setup/data/examples/examples_content1.sql` there is a line break in `!PREFIX!`

But there are more problems down the road:

```
Unable to execute SQL statement:
INSERT INTO `con_system_prop` SET `type` = 'stats', `name` = 'tracking', `value` = 'disabled'
Mysql Error: Table 'contenido.con_system_prop' doesn't exist (1146)
```

I gave up on this and installed without example data.

**Comment by dceonline** [comment]
This bug still exists. The insert line are split over multiple lines with line breaks. CONTENIDO cannot handle sql files with line breaks. Remove line breaks and demo client will be installed without errors

errorlog.txt entry
`INSERT INTO `con_content`
(`idcontent`, `idartlang`, `idtype`, `typeid`, `value`, `version`, `author`, `created`, `lastmodified`) VALUES
(20, 3, 22, 1, '2', '', 'sysadmin', NOW
(), NOW
())
 in /var/www/html/CONTENIDO/contenido/includes/functions.general.php on line 1565
[2021-09-28 14:58:43] Warning: "Database failure: 1630 (FUNCTION dev_con410.NOW does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual) - /CONTENIDO/setup/index.php?c=db&step=29 
INSERT INTO `con_content`
(`idcontent`, `idartlang`, `idtype`, `typeid`, `value`, `version`, `author`, `created`, `lastmodified`) VALUES
(21, 3, 4, 1, '2', '', 'sysadmin', NOW
(), NOW
())
" at reportHalt() [class.db.driver.handler.php(1009)]
	reportHalt() called in file class.db.driver.handler.php(981)
	halt() called in file class.db.driver.handler.php(702)
	query() called in file functions.sql.php(48)
	injectSQL() called in file include.db.controller.php(99)
	include() called in file index.php(43)`

**Comment by kw-pr** [comment]
This should fix it finally.

**Comment by muratpurc** [comment]
@kw-pr @dceonline is the issue finally fixed, and can we close the ticket?

**Comment by kw-pr** [comment]
Yes, thanks for asking.
