### ISSUE TITLE
[Feature] Include page title in search

### ISSUE THREAD

**Issue by kw-pr** [CONTENIDO/CONTENIDO#240]
I would like to include the page title in the search.

Feels wrong only content is included as the title is very important.

I already have a demo/hack for this but it does not work well.

contenido/classes/search/class.search.index.php

```
    public function addTitle(): void
    {
        global $cfg;
        $oDB = cRegistry::getDb();

        $sql = "SELECT *
            FROM " . $cfg["tab"]["art_lang"] . "
            WHERE
                idart = " . cSecurity::toInteger($this->idart); // AND idlang = " . cSecurity::toInteger($lang);"
        $oDB->query($sql);
        $oDB->nextRecord();

        $title = $oDB->f("title") . ' ' . $oDB->f("pagetitle");
        $firstItemKey = array_key_first($this->_keycode["CMS_HTML"] ?? []);
        if ($firstItemKey)
        {
            $this->_keycode["CMS_HTML"][$firstItemKey] .= ' ' . $title;
        }
    }
```

Also add `$this->addTitle();` in `start()` after `$this->_keycode = $aContent;`.

Note: I added title and pagetitle, maybe title is not needed.

How can I improve this?

**Comment by muratpurc** [comment]
@kw-pr  this won't work like this, we need to pass the language id, eventually the client id to the class cSearchIndex and/or t its start() function.

**Comment by kw-pr** [comment]
Or maybe we can add the title in $aContent from:

    public function start($idart, $aContent, $place = 'auto', $cms_options = array(), $aStopwords = array())

It is already an array with all the content. We could add it as `CMS_TITLE`.

Maybe in `conGenerateKeywords()`?

**Comment by kw-pr** [comment]
I added the language id and created a pull request for this:
https://github.com/CONTENIDO/CONTENIDO/pull/271
