### ISSUE TITLE
Discuss reason of "sleep(5)" in cAuthHandlerFrontend

### ISSUE THREAD

**Issue by ChristianJohn-Softwareentwicklung** [CONTENIDO/CONTENIDO#241]
Hi, 

what is the need in cAuthHandlerFrontend's function validateCredentials() for sleep(5) in line 153.
If you use wrong login credentials the scripts waits 5 seconds to lead you to the wrong login page. 

This behavior is irritating. 

The only reason for the existence seems to be brute force attacs. But there are better ways to do this. 

My suggestion is to remove the sleep(5); line.

**Comment by muratpurc** [comment]
Hi @ChristianJohn-Softwareentwicklung,

the `sleep(5)` has an imporant purpose, it prevents the page from brute force attacs by limiting failed login attempts.

**Comment by gonatan** [comment]
> But there are better ways to do this.

@ChristianJohn-Softwareentwicklung What do you have in mind?

**Comment by ChristianJohn-Softwareentwicklung** [comment]
Thanks for your quick feedback, 

@purcaholic: my understanding for a sleep command is only a delay and not a limiting. If you send a brute force attack with e.g. 1k requests, all of them reaches the scripts. I think an attacker would not be bothered by a 5 seconds limit. But it bothers users who type their password in a wrong way and has to wait. 

@gonatan: captchas, 2FA is to much in this case, but counting wrong login attemps and then do limiting or delaying is a possible way. 

For example 
When failed login, count the login attemps by ip or by user. after 10 attemps block for the next 3 minutes.

**Comment by kw-pr** [comment]
It limits the amount of passwords that can be tried per second. Without it the only limit is how fast your server is. 

This is a common approach see https://unix.stackexchange.com/questions/2126/why-is-there-a-big-delay-after-entering-a-wrong-password

Of course the delay is only needed after failed logins.

**Comment by kw-pr** [comment]
I made a push request with 2 seconds delay instead of 5.
That should be better for the user experience and enough for security.
