### ISSUE TITLE
No upload directory is set in CMS_IMGEDITOR on load 

### ISSUE THREAD

**Issue by ChristianJohn-Softwareentwicklung** [CONTENIDO/CONTENIDO#242]
Hi, 
if you have choosen an image in CMS_IMGEDITOR which is stored in a subdirectory of upload, the upload-path is not set on loading. 

If you open the imgeditor in the backend the correct path and image ist active / shown in the directory listing. If you click on upload the path is the root upload path until you click again on the active folder in the dirlist. 

Fix for this might be to call the showFolderPath-Function in **contenido\scripts\content_types\cmsImgeditor.js** after directory list has shown.
```
function cContentTypeImgeditor.prototype.addTabbingEvents
....
// if the upload tab is shown, show the directories tab, too
            if ($(this).hasClass('upload')) {
                $(self.frameId + ' .tabs #directories').show();
++              self.showFolderPath();**                
            }
```

Christian

**Comment by muratpurc** [comment]
Thank you for the bug report and for the fix.
