### ISSUE TITLE
functions_ general str_repeat(): Second argument has to be greater than or equal to 0, 1186

### ISSUE THREAD

**Issue by Faar400** [CONTENIDO/CONTENIDO#245]
There is a php-7.2-warning at line 1186 in functions.general.php if $props["level"] is smaller than or equal to 0.
`str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", $props["level"] - 1)`
It means, there are too less levels found in row 1158 (sql2), because "level" - 1 = -1

It was expectet to have levels in con_cat_tree but if it doesn't, str_repeat() has a second argument which is smaller than 0.
Why there are no levels exists is another question but it shold not throw a php-warning because it.
It is a minor thing but fixable in code.
Put this in row 1186 above $spaces ...
`if($props["level"] < 1)$props["level"] = 1;`

Otherwise this php-warning is filling the error-logfile very quickly.
Maybe its a kinda of quick&dirty coding, because levels should perhaps not be 0 but strepeat() expects at least 0.

**Comment by Faar400** [comment]
In the database concerned, I found several idcats with level = 0 in the con_cat_tree table.
Thats why 0 - 1 = -1

**Comment by Faar400** [comment]
I found 25 hits with str_repeat() in CONTENIDO.
One of them is this above in functions.general.php
One is in class.modrewrite_contenttest_controller.php in line 147.
`$pref = str_repeat('    ', $v['level']);`
I guess, 'level' means category-levels?
Even if level is 0, in this case it should not throw a fatal-error.
In class.requestvalidator.php there is a substraction too like in functions.general.php bit different in one point:
`str_repeat(' ', 17 - cString::getStringLength($_SERVER['REMOTE_ADDR']))`
str_len cannot be lower than 0, so 17 - 0 will be at least 17.
Other str_repeat() occourances are similar or inside external code like from Smarty or Swiftmailer.

In my conclusion, the pull-request https://github.com/CONTENIDO/CONTENIDO/pull/246 will solve the problem with str_repeat() in CONTENIDO. Because that's the only part where the second paramter of str_repeat() can be lower than 0.
Other opinions?

**Comment by muratpurc** [comment]
@Faar400 it should be enough to fix or adapt those occurances of str_repeat() where we generate similar indentation, e.g. by multiplying the string "\&nbsp;\&nbsp;\&nbsp;\&nbsp;...".

**Comment by Faar400** [comment]
@purcaholic In other occurances of str_repeat() inside CONTENIDO Core there was (in my opinion) no possibility for the second parameter to get lower than 0.
This one parameter `$props["level"] - 1` in functions.general.php was the only one which can be lower than 0, because "level" can be 0.
 Once i found a very little posibility to get NULL, but NULL is not 0 and that's not the concern of str_repeat but of the previous code.

**Comment by Faar400** [comment]
Because https://github.com/CONTENIDO/CONTENIDO/pull/253 the code in functions.general.php has changed and this issue should be solved now.
