### ISSUE TITLE
Forum unreachable

### ISSUE THREAD

**Issue by dceonline** [CONTENIDO/CONTENIDO#247]
@gonatan, seems to be an outdatet cert.

![grafik](https://user-images.githubusercontent.com/8067791/166240073-639c8feb-0156-47b6-8c7e-6b282f00e0c5.png)

**Comment by gonatan** [comment]
@dceonline Fulai Zhang will hav a look at this issue. Unfortunately I cannot add her as collaborator .. I don't have the privileges to do so (anymore?).

**Comment by dceonline** [comment]
Thx! Seems i also can't add @fulaizhang.

**Comment by Faar400** [comment]
They should not use HSTS

**Comment by gonatan** [comment]
@Faar400 Who is "they"? and why should HSTS not be used?

**Comment by dceonline** [comment]
"they" may be the serveradmin. Using HSTS normally is good, u just have to update your certs automatically.

**Comment by gonatan** [comment]
I don't get the point. Why should HSTS not be used if the certificates are not updated automatically?

**Comment by dceonline** [comment]
Well, if you dont use it, the visitor will be prompted to use an exclusion. If the server uses HSTS this isn't shown.

![grafik](https://user-images.githubusercontent.com/8067791/166446952-36cc65be-6044-4370-8d10-a2b3b7b6a551.png)

**Comment by gonatan** [comment]
This is correct and the main intention of HSTS.
Fulai is in progress to fix the problem so there is no need to deactivate HSTS.

**Comment by Faar400** [comment]
dceonline already said it, if it would be updated automatically, it would be no problem.
Otherwise users will be locked out.

**Comment by gonatan** [comment]
The certificate has been updated. The forum is available again.
