### ISSUE TITLE
Sending Emails from CONTENIDO Forum does not work

### ISSUE THREAD

**Issue by Faar400** [CONTENIDO/CONTENIDO#248]
Sending emails in the CONTENIDO forum does not work.
Neither does it reset the password.
I was asked to help, because one forgot his password and cannot login to the forum.

And still i cannot label this issues.

**Comment by dceonline** [comment]
Hi @fulaizhang, can u please check this?

**Comment by dceonline** [comment]
So i send a testmail from acc - works
i send an password request email - works
@Faar400, can u test it to?

**Comment by Faar400** [comment]
I've sent a mail to myself with my Acc and it worked.

**Comment by dceonline** [comment]
Seems to be fixed. Closed.
