### ISSUE TITLE
Website/Docs: Generate API documentation for 4.10.* versions

### ISSUE THREAD

**Issue by dodomedia** [CONTENIDO/CONTENIDO#250]
On the page https://www.contenido.org/deutsch/hilfe/api-dokumentation/index.html the API documentations of the versions 4.10.0 and 4.10.1 are missing.

**Comment by dceonline** [comment]
@gonatan Who has access and could do that?

**Comment by muratpurc** [comment]
@dodomedia generated API documentation for 4.10.0 and 4.10.1 can be downloaded from the related topic in CONTENIDO forum:

https://forum.contenido.org/viewtopic.php?f=115&t=43495
https://forum.contenido.org/viewtopic.php?f=115&t=43766

It would be great, if someone can provide them on the proper [CONTENIDO page](https://www.contenido.org/deutsch/hilfe/api-dokumentation/index.html).

**Comment by Faar400** [comment]
Who could do this?

**Comment by gonatan** [comment]
Done.
Please see https://www.contenido.org/deutsch/hilfe/api-dokumentation/index.html.

**Comment by gonatan** [comment]
closed

**Comment by Faar400** [comment]
@gonatan thanks :-)
