### ISSUE TITLE
MySQL 5.5 and CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#268]
A user has reported issues during the installation of the current (7th June 2022) develop-branch on an environment using MySQL 5.5.

The usage of `CURRENT_TIMESTAMP` as default value for database fields of type datetime doesn't work, `CURRENT_TIMESTAMP`, and `NOW()` are supported as of [MySQL 5.6.5](https://dev.mysql.com/doc/refman/5.6/en/timestamp-initialization.html).

I suggest that we should not try to be compatible with MySQL-Versions older than 5.7 (or 5.6.5), the required changes in CONTENIDO would make the code more compilcated and harder to maintain. 

My proposal would be to drop support for MySQL older than 5.7 or 5.6.5. Any other ideas?

See also related post in CONTENIDO forum:
https://forum.contenido.org/viewtopic.php?f=115&t=44468#p182711

**Comment by Faar400** [comment]
Instead of current_timestamp() I would use now(), current_timestamp is just an alias of now.
In conclusion, it follows that I consider the use of NOW or current_timestamp to be correct.
When we think of older version updates, do we also think of PHP version updates, and why not database version updates as well?
If you create new databases, you will no longer get 5.6.x MySQL, but at least 5.7.x, if not even 8.x
It's much easier to export database-tables and import it in an new one than Contenido-Modules adapt to PHP 7.4 or 8.x

**Comment by muratpurc** [comment]
> Instead of current_timestamp() I would use now(), current_timestamp is just an alias of now.

Yes, we could use `NOW()` instead of the alias `CURRENT_TIMESTAMP`, but I'm not sure if we should change the sources again, we already changed the code to use `CURRENT_TIMESTAMP` in current development branch.

> If you create new databases, you will no longer get 5.6.x MySQL, but at least 5.7.x, if not even 8.x

This is most likely the case for the largest part of providers, but we still have some community user running a server with several PHP versions (5 & 7) and an old MySQL 5.5 server. But, if you ask me, my opinion would be to drop support for MySQL versions older than 5.7.

**Comment by Faar400** [comment]
> But, if you ask me, my opinion would be to drop support for MySQL versions older than 5.7.

I think the same.

**Comment by muratpurc** [comment]
As a note on the topic:
CONTENIDO does not support MySQL 5.5 since version 4.9.0 Alpha 1, see [CHANGELOG.txt](https://github.com/CONTENIDO/CONTENIDO/blob/develop/CHANGELOG.txt#L2012)

**Comment by muratpurc** [comment]
Support for MySQL 5.5 was already dropped a long time ago. The End-Of-Life for MySQL 5.7 is in [October 2023](https://endoflife.date/mysql), But we still support MySQL 5.7 for now.

This issue will be closed.
