### ISSUE TITLE
Adding CONTENIDO version to the generated meta tag should be configurable

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#30]
Generation of the metatag name="generator" adds the CONTENIDO version to the metatag, see contenido/classes/code_generator/class.code.generator.standard.php, between line 510 - 523. There is already a flag ($addVersion) to control this behavior but it is hard coded there.

The flag to add the version to the metatag should be configurable. Some user have legitimate concerns to being atatcked, once a security issue for a specific version gets well known.

**Comment by muratpurc** [comment]
There is a new setting for this.

```
Type: generator
Name: add_version
Default Value: true
```

Keep in mind to update the docs!
