### ISSUE TITLE
Setup: Check for redundant & wrong primary keys before setting auto-increment attribute

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#31]
Some older Contenido 4.8 installations may contain tables with invalid primary key values, those could be:
- Entry with primary key having the value 0
- Multiple entries with same primary keys

Assigning the auto-increment attribute to the primary key fields will result in errors. The setup process could be extended to check the tables for those invalid entries before running the update.

See related topic in forum: https://forum.contenido.org/viewtopic.php?t=43479

**Comment by tone2tone** [comment]
I went through an old 4.8.20 database and compared it to a 4.10.1 database. If I am not mistaken, the only contenido core DB table that might cause errors is con_action with its entry " 0 - fake_permission_action" (in a new installation, this is set to id = 1, not 0).
Subsequently, quite a lot of entries exist in con_actionlog for idaction = 0 in old installations. 
It *might* be enough to check for con_action id=0, address a new id and just for the sake of it amend all con_actionlog entries during setup. 
All other tables are not our main concern and would require adjustment by the addon developer. We *could* check for all database tables though, and whenever it is not con_action tell during setup process  which tables need to adjustment by hand.
Thoughts?
