### ISSUE TITLE
Deprecated md5.js

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#315]
At contenido/scripts/md5.js I found a deprecated JS which is no longer supported since 2015-05-21.
I could not find any usages of this script in the CONTENIDO core.
Should we just remove it?

**Comment by muratpurc** [comment]
> Should we just remove it?

Yes, I think we can easyly remove a file, which is not used by CONTENIDO and is marked as deprecated since almost eight years.
