### ISSUE TITLE
Compatibility with PHP 8.1

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#342]
Make CONTENIDO sources compatiblw with the PHP 8.1 release.

See official migration guide for more details:
https://www.php.net/manual/en/migration81.php

**Comment by Faar400** [comment]
This makes me happy but some Hosters didn't provide PHP 8.1 or even 8.2 already.

**Comment by muratpurc** [comment]
> This makes me happy but some Hosters didn't provide PHP 8.1 or even 8.2 already.

It’s better to prepare CONTENIDO for PHP 8 and PHP 8.1 now, when we have the resources to do it.

**Comment by Faar400** [comment]
yes, indeed.
