### ISSUE TITLE
fatal error when saving modul input or output

### ISSUE THREAD

**Issue by markushuebner** [CONTENIDO/CONTENIDO#368]
PHP 8.0.27
Contenido DEV-Version 28.02.2023
local development within xampp
-----------------------
When saving changes within module input or output, there only appears a blanc frame afterwards. Errorlog reports on this:

```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + int in C:\xampp\htdocs\contenido\classes\version\class.version.php:467
Stack trace:
#0 C:\xampp\htdocs\contenido\classes\version\class.version.php(350): cVersion->getRevision()
#1 C:\xampp\htdocs\contenido\includes\functions.mod.php(64): cVersion->createNewVersion()
#2 C:\xampp\htdocs\contenido\includes\type\action\include.mod_edit.action.php(47): modEditModule('5', 'content_header_...', '', '', '<?php\r\n\r\n/**\r\n ...', '', 'content')
#3 C:\xampp\htdocs\contenido\main.php(200): include_once('C:\\xampp\\htdocs...')
#4 {main}
  thrown in C:\xampp\htdocs\contenido\classes\version\class.version.php on line 467
```
This problem can be solved via changing line 467
from
`$this->iVersion = ($this->iRevisionNumber + 1) . '_' . $this->dActualTimestamp;`
to
`$this->iVersion = (intval($this->iRevisionNumber) + 1) . '_' . $this->dActualTimestamp;`

**Comment by muratpurc** [comment]
Thank you for the report, it has been fixed.

**Comment by markushuebner** [comment]
> 

That was lightning fast, Murat! :)

**Comment by muratpurc** [comment]
I had the project open in front of me anyway and this was a low hanging fruit. Thanks again for reporting, Markus.
