### ISSUE TITLE
cAuth calls abstract methods of cAuthHandlerAbstract

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#38]
Abstract methods of the class cAuthHandlerAbstract are called in class cAuth, although cAuthHandlerAbstract inherits cAuth.

It should be checked if we could merge both classes as cAuthHandlerAbstract and make cAuth a deprecated alias for this class.

**Comment by tone2tone** [comment]
If I get it correct, cAuth holds methods that apply to frontend AND backend authentication, where handling of both auth processes is basically identical. The abstract layer of it would allow to then go for different use cases, where frontend and backend handling of auth differs.
The only method right now in cAuth that tries to use its "child" is `_fetchLoginForm()` , and to be honest, I am not sure what this function is trying to achieve at the end. It calls `$this->displayLoginForm();` , an abstract function with no code at all. 
Up to now, login forms are not produced here, so I am not sure what kind of "LoginForm" this function is going for. Depending on what it wants to achieve, this function might have to be reworked or shifted to the abstract class or the function of the abstract class will have to be shifted to cAuth. 
Thoughts?
