### ISSUE TITLE
sizeof(): Argument #1 must be of type Countable in class.debug.visible.adv.php

### ISSUE THREAD

**Issue by Faar400** [CONTENIDO/CONTENIDO#384]
Since PHP 8.x an Fatal error ist thrown in row 218 of class.debug.visible.adv.php, if NULL is given.
Row 112 uses with _if ($this->count() > 0)_ the own public function _count()_ in row 218 and obviously __aItems_ is not countable, because NULL is given.
I don't know where the NULL comes from and what conclusion is about this misleading value but perhaps in row 218 should be checked for _is_countable()_ first, to avoid fatal errors.

**Comment by muratpurc** [comment]
Please provide a step by step example or a stacktrace so we can reproduce this issue. Your solution fixes the error, we should find and fix the root cause.

This shouldn't normally happen, since you have to instanciaste the class and it's constructor sets the property `$this->_aItems` as an empty array. 

If your PHP version is between 8.1.0 and 8.1.5, then the [PHP OPcache bug ](https://github.com/php/php-src/issues/8164) could be the reason for your issue.

**Comment by Faar400** [comment]
`[02-Aug-2023 13:12:51 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, null given in /contenido/classes/debug/class.debug.visible.adv.php:218
Stack trace:
#0 /contenido/classes/debug/class.debug.visible.adv.php(112): cDebugVisibleAdv->count()
#1 /contenido/classes/debug/class.debug.php(150): cDebugVisibleAdv->showAll()
#2 /contenido/classes/class.registry.php(734): cDebug::showAll()
#3 /contenido/main.php(229): cRegistry::shutdown()
#4 {main}
 thrown in /contenido/classes/debug/class.debug.visible.adv.php on line 218`

**Comment by Faar400** [comment]
CONTENIDO Version | 4.10.2-dev
Webserver-Version | Apache
Installierte PHP-Version | 8.1.13
Datenbankserver-Version | 8.0.25-15
PHP-Datenbankerweiterung | mysqli

**Comment by Faar400** [comment]
What i did is just switch on both the debug messages in system-->configuration and clicking arround in the website and backend.
So i have a lot of such fatal errors in different cases.

**Comment by muratpurc** [comment]
Thank you for providing the stack trace, my development setting is almost like yours.

- Windows 10 Pro
- PHP 8.1.5
- Apache 2.4.43
- MariaDB 10.4.11

Unfortunately, I couldn't reproduce your reported issue. But I get another error log entry, which is reproduceable:
````
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in contenido/classes/debug/class.debug.visible.adv.php on line 130
````
The property `$this->_buffer` has the value `null` at that point, therefore it shouldn't passed as the third parameter to the function `str_replace()`.

Back to topic:
We should find the reason, why the property `$this->_aItems` is not set in your case, which should happen in the constructor, according to the programming logic. I assume that something different causes this issue.
