### ISSUE TITLE
Second parameter in constructor of cApiArticleLanguage

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#39]
In class cAjaxRequest the constructor of cApiArticleLanguage is called with a second parameter which does not exist. This parameter should be removed.

**Comment by muratpurc** [comment]
Already fixed with commit https://github.com/CONTENIDO/CONTENIDO/commit/eaa183b94d6ebd809aa3a616f7cf93cd082d17a6.
