### ISSUE TITLE
[Bug?] logfile contents are not shown anymore in contenido backend

### ISSUE THREAD

**Issue by tone2tone** [CONTENIDO/CONTENIDO#406]
With the latest dev installed, it seems that the content of the log files is not displayed anymore in Contenido's backend administration. The file size is properly shown, yet nothing within the textarea.

**Comment by muratpurc** [comment]
Please check your setting `$cfg['system_log']['default_memory_limit']` in file `data/config/production/config.misc.php` and your PHP ini setting `memory_limit`.

If you have log files that are larger than the value defined in this setting (default is 64MB) or in the PHP ini, then the contents of these log files will not be displayed.

The log files are still listed in the dropdown, and a note is displayed in red that the log file is too large to be displayed. However, you can delete log files that are too large.

The logic for determining the memory limit, which is used as a limit for log files to be displayed, can be found in the file include.system_log_sysvalues.php on lines [30-34](https://github.com/CONTENIDO/CONTENIDO/blob/0050d9180810150ee4f692b9c4b4638690d8ac37/contenido/includes/include.system_log_sysvalues.php#L30-L34).

**Comment by tone2tone** [comment]
That's not the problem here. All logfiles are only a few kb in size, and 64 MB is the standard setting default in my configs (I checked that to be sure). Yet, I have a few upgraded installations where no content is shown as described, and I can't delete the files through the admin interface. I have to delete them physically through FTP, yet, after that, I can't access or delete the new files the system creates. Strange.

**Comment by muratpurc** [comment]
It is unusual that the content of a log file that is not too large is not displayed.

Do you use any symlinks and did you also check the permissions the affected log files?

You can debug what happens in file `include.system_log_sysvalues.php` between the lines [116-121](https://github.com/CONTENIDO/CONTENIDO/blob/0050d9180810150ee4f692b9c4b4638690d8ac37/contenido/includes/include.system_log_sysvalues.php#L116-L121).

**Comment by tone2tone** [comment]
Okay, false alert. I had to delete all cookies and browser cache for this site, enter backend again, then it worked. Strange that this never caused a problem with other installations. Don't know which cookie or cache file restricted jquery from working on this specific subpage.
