### ISSUE TITLE
Logfile flooded by cTypeGenerator

### ISSUE THREAD

**Issue by tone2tone** [CONTENIDO/CONTENIDO#407]
For some modules, I create an amount of cms-types to use them dynamically for remixed input possibilities. As an example, one version to open 10 containers of each type is as follows:
```
$typeGen = new cTypeGenerator();
$containerId = cRegistry::getCurrentContainerId()*10;
// lege für die meisten CMS-Typen 10 Stück an
for ($i = $containerId; $i < ($containerId + 10); $i++) {
	$header[] = stripslashes($typeGen->getGeneratedCmsTag('CMS_HTMLHEAD', $i));
	$text[] = stripslashes($typeGen->getGeneratedCmsTag('CMS_HTML', $i));
	$date[] = stripslashes($typeGen->getGeneratedCmsTag('CMS_DATE', $i));
	$imageEditor[] = $artLang->getContentObject('CMS_IMGEDITOR', $i);
	
}
```
This is no problem for CMS_HTMLHEAD, CMS_HTML and CMS_IMGEDITOR.
CMS_DATE though produces a large amount of entries in deprecatedlog.txt, all stating:

> Deprecated call: formatToDate() [class.date.php(192)]: "The function `strftime()` is deprecated as of PHP 8.1.0, and the passed format string was detected as a `strftime()` format. The `date()` function will be used as a fallback, but without localization support."
> 	formatToDate() called in file class.content.type.date.php(266)
> 	_formatDate() called in file class.content.type.date.php(94)
> 	__construct() called in file class.typegenerator.php(158)
> 	_processCmsTags() called in file class.typegenerator.php(183)
> 	getGeneratedCmsTag() called in file include.front_content.php(739) : eval()'d code(169)
> 	eval() called in file include.front_content.php(739)
> 	include() called in file front_content.php(43)

Instead of ignoring a still empty or not available cms_date, cTypeGenerator floods the logfile to a point where it holds 100MB and more after a few page impressions.

**Comment by muratpurc** [comment]
The content type CMS_DATE uses `strftime` formats to display localized month names or week days, but `strftime` is deprecated since PHP 8.1. 

The entry you described is triggered by calling a date format function within the `class.content.type.date.php` and the entry is meant as an indication that a deprecated function is being used.

Unfortunately there is no simple solution to solve this at the moment. We could use the `ext-intl` extension, which tightens the requirements for CONTENIDO.

But you can disable the logging of deprecations by setting following configuration:
````
$cfg['debug']['log_deprecations'] = false;
````

**Comment by tone2tone** [comment]
Yes, but that's not my initial problem. I could live with a deprecation info on a date that is set and being handled in strftime. BUT the deprecation error is thrown even if the date field is not set yet. It would reduce the bulk of deprecation notes if there was a check beforehand that there is no timestamp to process at all. In the long run, I would have to disable logging perhaps for existing dates, but that is step 2. 
Does this PHP functionality help in any way to replace strftime?
https://www.php.net/manual/de/intldateformatter.format.php

**Comment by muratpurc** [comment]
Whenever you open the "Raw Data", "Editor" and "Preview" tab in the backend, an instance of the TinyMCE editor `cTinyMCE4Editor` is created in the page, which in turn creates instances of all content types, including `CMS_DATE`, if this is configured somewhere on the page.

Depending on the tab, it can happen that the instances of all content types are created 2 or 3 times in different places and an instance of `CMS_DATE` currently ensures that 5 entries end up in the `deprecatedlog.txt`.

I understand that the number of entries becomes too much in the long run and we need a solution for this. Until then, I can only recommend that you switch off the logging of deprecated logs.

Regarding your question about IntlDateFormatter:
Yes, this would help and this is exactly what the PHP extension `intl` requires, i.e. this extension must be installed on the system and activated in PHP, which increases the PHP requirements for CONTENIDO.

**Comment by muratpurc** [comment]
@tone2tone The logging of deprecated usage of strftime formats has been optimized, it will log one entry per request lifecycle, and this should alleviate the problem.

Thanks for your help.
