### ISSUE TITLE
UI issues in backend edit mode

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#415]
A user reported in the forum about problems with the WYSIWYG editor that occur in Firefox when editing the article.

1. The markup for the content_text module is rendered at the end of the parent element in Firefox. Wrapping the template variable $text solved the problem.
2. The bar of the inline TinyMCE editor appears when the article is opened in edit mode, the initial cleaning and setting of the markup creates a focus event, which in turn displays the bar
3. When maximizing the inline TinyMCE editor, other elements (e.g. '.cms_abstract_img' or '.cms_date .ui-datepicker') that have a high z-index may appear on top of the editor.

See post in the forum:
https://forum.contenido.org/viewtopic.php?f=115&t=44693

**Comment by tone2tone** [comment]
I can confirm those behaviours too. In most of my self written modules, I had to wrap all content_editors (and labels sometimes too) to re-adjust the buttons for edit/save a content element. I don't know if it has to do with bootstrap running (through my layout).
TinyMCE popping up with the inline editor mode when is something I come across a lot too; I cannot validate my hunch but it feels like it appeared first when updating my projects from php7.4 to 8.0 and a contenido developer version from around September 2022.

**Comment by muratpurc** [comment]
The user who reported this in the forum does not use a JavaScript framework or library in the frontend and the JavaScript used has no influence on the order of the content elements that are initialized with the TinyMCE editor, even if the JavaScript of the frontend is deactivated. Wrapping seems to work very well atm, until we know the exact cause and have a solution for it.

The small bar of the TinyMCE editor also appears in a CONTENIDO 4.10.1 installation. This is an indication for a Firefox or TinyMCE issue if the problem arose around September 2022, because CONTENIDO 4.10.1 was released almost three years before.
