### ISSUE TITLE
Call statistics are not correct

### ISSUE THREAD

**Issue by achiWare** [CONTENIDO/CONTENIDO#423]
In the class class.registry.php the method isTrackingAllowed() returns an incorrect return value.

**actual:**
return cSecurity::toInteger($_SERVER['HTTP_DNT'] ?? '0') === 1;

**correct:**
return cSecurity::toInteger($_SERVER['HTTP_DNT'] ?? '0') != 1;

[https://forum.contenido.org/viewtopic.php?f=115&t=44718](https://forum.contenido.org/viewtopic.php?f=115&t=44718)

**Comment by dceonline** [comment]
Confirmed.
