### ISSUE TITLE
Update Smarty

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#437]
Update Smarty template engine

**Comment by dceonline** [comment]
@muratpurc Please also update plugin.xml requirements and version. Smarty dropped support for PHP7.1, so i think we have to increase also PHP requirements and needed CONTENIDO version for smarty plugin.

**Comment by muratpurc** [comment]
> @muratpurc Please also update plugin.xml requirements and version. Smarty dropped support for PHP7.1, so i think we have to increase also PHP requirements and needed CONTENIDO version for smarty plugin.

@dceonline  Thanks for the comment.

According to the readme, the [Smarty version 4.3.4](https://github.com/smarty-php/smarty/tree/v4.3.4) (release from Oct 1st, 2023) used in CONTENIDO supports PHP 7.1 to PHP 8.2, but in the master branch they have upgraded this to PHP 7.2 to PHP 8.3.

The PHP requirements in CONTENIDO have therefore been adjusted from >= 7.0.0 to >= 7.1.

If the new Smarty version used in CONTENIDO expects at least PHP 7.2, you are right, then this needs to be adjusted in CONTENIDO too.

**Comment by dceonline** [comment]
@muratpurc 
Hi Murat, no, that's not what i meant. 
If one updates or enhance CONTENIDO plugins, imo he also has to "update" version and requirements in the [plugin.xml](https://github.com/CONTENIDO/CONTENIDO/blob/develop/contenido/plugins/smarty/plugin.xml) of the plugin.
What do you think about that?

**Comment by muratpurc** [comment]
@dceonline Yes, you are absolutely right, the plugin.xml of the smarty plugin needs to be adjusted. Thank you.
