### ISSUE TITLE
Content / Translations: amount of templates (in use) is wrong

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#53]
On the translations page, the "In use by" always displays "1 Template", but clicking on the "i"-Icon on "content_date" shows much more templates, where the module is used in.

**Comment by tone2tone** [comment]
@gonatan Sorry to say I can't reproduce that behaviour in develop branches and live 4.10.1 versions. Even in some of my weird multilingual websites all entries are "clean" - the amount of templates shown in table and the amount of names in the popup are always fitting. I suspect this behaviour to appear on websites that have been updates a lot over the years and come with database junk of not properly deleted entries (?).

**Comment by muratpurc** [comment]
@gonatan @tone2tone I couldn't reproduce this issue on current development branch either, we may consider to close this issue.

**Comment by gonatan** [comment]
As this was one of the old Jira tickets I moved to Github just let's close this issue. @purcaholic Thanks for checking! :)
