### ISSUE TITLE
Content / Articles: Make category online/offline sometimes does not work

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#55]
Select a category in Content / Articles. Click on "Edit category" and then on "Online / Offine". The function works as expected.

Now select the template "None" and save it by hitting the arrow icon. Clicking now on "Online / Offline" does not work any longer. A JS error is raised:

Uncaught TypeError: Cannot read property 'replace' of undefined

**Comment by tone2tone** [comment]
@gonatan I can't reproduce that behaviour in the current develop branch. I specifically deleted the category AND the article template in both possible combinations (keepin one or the other, or deleting both), but never came across the JS error.

**Comment by muratpurc** [comment]
@gonatan @tone2tone Same here, I couldn't reproduce this issue on current development branch either, therefore I suggest to close this issue.

**Comment by gonatan** [comment]
As this was one of the old Jira tickets I moved to Github just let's close this issue. @purcaholic Thanks for checking! :)
