### ISSUE TITLE
Content / Articles: Publish date of article does not get updated fast enough

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#56]
In the articles overview page, clicking on "Make online" will switch the article online, but the page nevertheless says "not yet published" for this article. When the page gets reloaded, the publish date is correct.

**Comment by tone2tone** [comment]
The assumption that it is a delay issue is not correct. The error occurs in include.con_art_overview.php, line 655: the check on publishing state is done on a string ('1') instead on a numeric (1) as it SHOULD be which causes the value to be false at all times when changing the publishing state of an article by clicking on the icon in the article list.
Pull request to fix this has been added.
