### ISSUE TITLE
Articles overview: handle large amount of pages

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#57]
When there is a really large amount of articles in a category which produces a lot of page links, the layout in the articles overview page gets much unusable. Please find a way to handle large amounts of pages (100+).

**Comment by muratpurc** [comment]
The article overview has been optimized. The rendering time has been reduced from around 1.05 seconds to around 0.26 seconds for category with 500 articles with different properties. That should be enough for now.
