### ISSUE TITLE
Performance issues on systems with many articles

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#61]
With a setup of 50,000+ articles the backend article search and the synchronization of modules (after a change, not always) takes too long time to finish. Please check if this task can be made faster.

**Comment by tone2tone** [comment]
To be honest, I'd say: Contenido was NEVER meant for such an amount of articles. I think in my biggest biggest projects I made it up to article IDs in the range of 4.000, and THAT to me seemed huge. Trying to tweak Contenido's backend performance for setups with 50.000+ articles would have no priority to me.
That saying, I would be interested to know what "too long time to finish" means.. what time intervalls are we talking about here?

**Comment by dceonline** [comment]
Well, CONTENIDO can handle much more articles, and i had some customers with a real big count. But - there are a few design flaws that, depending on the number, can result in a memory overflow. I changed this in my ConLite, the fork of the 4.8 version, using a modified article collector class. Maybe you check this out in class cArticleCollector and how the array for articles is build there.

**Comment by muratpurc** [comment]
The article search has been reworked, it uses a similar approach as the article overview, in which recurring and/or computationally intensive processes or database queries are reduced as much as possible.

The result of a CONTENIDO installation with approx. 2100 articles is as follows.

**Before the optimization**

- Search result: 2062 articles
- Database queries: 2836
- Total search processing time: about 2.8 seconds

**After the optimization**

- Search result: 2062 articles
- Database queries: 6
Total search processing time: about 0.7 seconds

I'll do some fine-tuning and tests, before I'm going to merge the changes into the dev branch.

**Comment by gonatan** [comment]
GREAT!!!
