### ISSUE TITLE
Multiple issues with cEffectiveSetting class

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#63]
There are multiple issues with the cEffectiveSetting class, which must be fixed:
- Calling the class on plugin loading context, when lang and client variable are not yet set the class will store empty classes for clientLanguage and probably client, because the IDs are unknown. Remove the usage of the global variables and use the cRegistry getter methods for the client and the language ID
- Check the instances of user, client and client language if they are loaded (with the correct ID, not just a random object) before storing them in the static variable.
- Unsetting the instances in the method reset should be changed to setting these variables explicitly to NULL (like the settings array is set to an empty array)

**Comment by muratpurc** [comment]
`cEffectiveSetting` class, respectively the `getEffectiveSetting` function, was never meant to be usable in a very early stage of CONTENIDO bootstrapping process. 

Inclusion of configuration files (`config.plugin.php`) of active plugins is done in `functions.includePluginConf.php`. This happens before setting client, user, language, database, article, category, etc...

The plugin configuration should ideally set only the configuration and should not have complex business logic or try to use functions being dependent on set client, user, language, etc...

**Comment by tone2tone** [comment]
@gonatan If I am not completely wrong, unset comes with no possibility of "setting" the unset-value. There is a method of casting "unset" which is not the same as the function unset PLUS it is deprecated from PHP 7.2 onwards.
https://www.php.net/manual/de/function.unset.php
@purcaholic Is there anything really to do on this ticket?

**Comment by muratpurc** [comment]
> @purcaholic Is there anything really to do on this ticket?

I don't know, if we should try to find a solution for this issue. On the one hand we have an issue here, and on the other hand, this is related to a too early access to variables, which aren't set at that step. I would close this ticket I don't decide this on my own.

**Comment by gonatan** [comment]
@purcaholic @tone2tone

"was never meant to be usable in a very early stage of CONTENIDO bootstrapping process" is the key information. Thanks for that!

I would not change the current behaviour in general. Instead I would like to see the `class cEffectiveSetting` to be aware of this restriction.

1. Would it be helpful to amend the documentation of this class to outline this restriction?
2. Would it be possible to check if methods of this class can be called safely, i.e. after the initialization of "client, user, language, database, article, category, etc..."? Throwing an exception would be better than storing "empty classes".

On the other hand there are further improvements that could be done:

3. usage of "global variables" vs "cRegistry getter methods" in cEffectiveSetting
4. "Check the instances of user, client and client language if they are loaded (with the correct ID, not just a random object) before storing them in the static variable." This could be achieved by throwing an exception instead (see above).
5. "Unsetting the instances in the method reset should be changed to setting these variables explicitly to NULL (like the settings array is set to an empty array)" @tone2tone I would like to see the unsetting being **replaced** by setting NULL values. Reason for this is that "Static properties cannot be unset." At least that's what my IDE says ..

```
# current code
public static function reset() {
    self::$_settings = array();
    unset(self::$_user, self::$_client, self::$_clientLanguage);
}

# intended code
public static function reset() {
    self::$_settings = array();
    self::$_user = self::$_client = self::$_clientLanguage = NULL;
}
```

**Comment by muratpurc** [comment]
@gonatan Thanks for your suggestions. Throwing exceptions would be an option for a major version of CONTENIDO in my opinion, since it would change the current behavior. What do you think, should we postpone the exceptions part to a major CONTENIDO version?
