### ISSUE TITLE
Wrong Error-Message by Code-Flush

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#64]
If you clear the Cache via Contenido-Backend, the error-message which may appear if there are not enough permission is wrong:

![Auswahl_174](https://user-images.githubusercontent.com/4060949/69442697-551f9f00-0d4d-11ea-80e7-59c5dca45613.jpg)

As far as I know, there is no con_code Table anymore, because cache is saved on the disk in a folder.

**Comment by oldperl** [comment]
That' s correct, table con_code is gone since 4.9
