### ISSUE TITLE
Permission checks are not applied everywhere at Administration / System / WYSIWYG

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#69]
If permissions are missing settings for toolbars and contenido_lists are disabled, form save button is also disabled but "Additional parameters" can be entered and "TinyMCE 4 configuration for external plugins" form as well as the reset Configuration button are enabled.

**Comment by tone2tone** [comment]
@gonatan Sorry, have to ask: Are you talking about the possibility to set permissions for TinyMCE4? If so, where do you set them? Until now I thought there IS no user-/group-specific option to set permissions, and TinyMCE always works full blast, other than TinyMCE3 that was configurable through values in user-/group-rights setttings.

**Comment by muratpurc** [comment]
@tone2tone there are no TinyMCE4 specific settings at the moment. The class `cTinymce4Configuration` renders the TinyMCE 4 configuration form and depending on wheter the user is a sysadmin or not, the form elements are disabled, but this approach ist not consistently used for all form elements on the TinyMCE 4 configuration form.
