### ISSUE TITLE
Log error if mail fails to send

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#70]
cMailer (SwiftMail) is used to send Mails via Contenido.

Currently I have the issue (in Newsletter), that Mails won't send, but I got no usable feedback why.

Output Error-messages to Contenido-Error is needed here.

This can be made by ErrorLoger Plugin for SwiftMailer. http://swiftmailer.org/docs/plugins.html#using-the-logger-plugin

Init Logger after "new cMailer(), and output it to cWarning() .. here an example:

```
$mailer = new cMailer();
$logger = new Swift_Plugins_Loggers_ArrayLogger();
$mailer->registerPlugin(new Swift_Plugins_LoggerPlugin($logger));
$recipients = $mailer->sendMail($from, $recipient->get('email'), mi18n("NEWSLETTER_CANCEL"), $sBody);
if(!$recipients) cWarning($logger->dum());
```

**Comment by muratpurc** [comment]
This feature is implemented, there is a new system setting for this.

```
Type: system
Name: mail_log_error
Default Value: false
```
The logging of failed emails is disabled by default, the user has to enable it by configuring it via the proper system setting.

Keep in mind to update the docs!
