### ISSUE TITLE
getIdsByClientId for certain classes extending ItemCollection

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#72]
The classes cApiClientLanguageCollection and cApiCategoryCollection have methods to get the IDs of all its entities as an array belonging to a given client.

These methods are called getLanguagesByClient() and getCategoryIdsByClient() respectivly.

The class cApiClientLanguageCollection does not have any method providing this functionality.

All classes extending ItemCollection which represent an entity with a IDCLIENT property should provide a method with the same signature (public function getIdsByClientId($idclient)) providing the afore mentioned functionality.

Deprected methods should be marked as such and should create a deprecation log message.

**Comment by tone2tone** [comment]
@gonatan Sorry, not fully sure what you mean here plus some requests:
- First of all, you mention cApiClientLanguageCollection twice, but I think you wanted to refer to some other class on one occasion. Plz specify.
- Could you do some research work and go through all available subclasses of ItemCollection as shown here: https://api.contenido.org/latest/class-ItemCollection.html and check, where you think the aforementioned method is missing? That would be really helpful!

**Comment by muratpurc** [comment]
The first implementation of this feature was made in `cApiActionlogCollection` and in `cApiArticleCollection`.

**Example usage with `cApiActionlogCollection`:**

```php
$coll = new cApiActionlogCollection();

// Get all ids (idlog) by client id 1
$ids = $coll->getIdsByClientId(1);
var_dump($ids);

// Get all ids (idlog) by language id 2
$ids = $coll->getIdsByLanguageId(2);
var_dump($ids);

// Get all ids (idlog) by client id 1 and language id 2
$ids = $coll->getIdsByClientIdAndLanguageId(1, 2);
var_dump($ids);
```

**Example usage with `cApiArticleCollection`:**

```php
$coll = new cApiArticleCollection();

// Get all ids (idart) by client id 1
$ids = $coll->getIdsByClientId(1);
var_dump($ids);
```
