### ISSUE TITLE
Adapt/Fix Unit Tests for the Test Suite "frontend_html"

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#79]
Replace usage of missing `Util::callProtectedMethod` against proper implementation. Usage of `Assert::readAttribute` is [deprecated](https://github.com/sebastianbergmann/phpunit/issues/3338), replace this also against a proper implementation.

Some of the unit test will fail, since we have an internal counter for the id-attribute in `cHTML`, this means, that a creation of an element will set an id-attribute value, which is not empty, like it was in the past. Handle this in unit tests.

**Comment by gonatan** [comment]
> Usage of Assert::readAttribute is deprecated, replace this also against a proper implementation.

I've seen that and finally understood that some of my tests using this method are complete nonsense. So feel free to remove them instead of trying to adapt them.

**Comment by muratpurc** [comment]
The change for this issue was committet to another branch, see https://github.com/CONTENIDO/CONTENIDO/pull/80/commits/ee61f03706890a0b4ae94dc341b9a70a0d88208c.

**Comment by muratpurc** [comment]
Description of this issue has been moved to https://github.com/CONTENIDO/CONTENIDO/issues/78, closing this issue.
