### ISSUE TITLE
Duplicate class names in test cases

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#85]
The class name `cHtmlTest` is used twice, in `test/contenido/classes/html/class.html.test.php` and in `test/frontend/html/html_test.php`. The same case is for `cHtmlFormElementTest` (see `test/frontend/html/test_formelement.php` and `test/contenido/classes/html/class.html.formelement.test.php`). This prevents us from running all tests.

As far as I see, they test same features of the classes, and there is no need to have multiple/redundant tests. We should not use same class names for test cases and should merge unit tests of test case classes, testing same class, into one test case class.

**Comment by gonatan** [comment]
I will have a look at this issue this weekend ..
