### ISSUE TITLE
Replace date validation checks with a function call

### ISSUE THREAD

**Issue by muratpurc** [CONTENIDO/CONTENIDO#88]
We have several places in the code doing date checks like:
```
if ($date !== '0000-00-00 00:00:00' && $date !== '') {
    // do something
}
```

The check, if a value is a valid date or has a valid date syntax could be done by a function call. We could implement a `cDateValidator` class and a function in `functions.general.php`, which uses the validator, e. g.:
```
function isValidDate($date) {
    $validator = cValidatorFactory::getInstance('date');
    return $validator->isValid($date);
}
```

Then we could do the checks like
```
if (isValidDate($date) {
    // do something
}
```

Using the function `isValidDate()` moves the logic of validation into one central place and reduces the complexity.

**Comment by gonatan** [comment]
Perfect! I propose to do that in v4.10.3 as it's an enhancement that is not that urgent, right?
Unless you or someone else is keen on implementing this .. :)

**Comment by muratpurc** [comment]
@gonatan I'm fine with adding this to milestone 4.10.3.
